# GAME CONSTANTS
SCREEN_WIDTH = 400
SCREEN_HEIGHT = 600
GRAVITY = 0.08
FLAP_STRENGTH = -7
PIPE_SPEED = 6
PIPE_GAP = 150
PIPE_SPACING = 200  # Distance between pipes

# REWARD CONSTANTS
SURVIVAL_REWARD = 1
FLAP_REWARD = 0
PIPE_PASSED_REWARD = 10
COLLISION_REWARD = -100
OUT_OF_BOUNDS_REWARD = -1000
